# Generated by Django 4.2 on 2025-03-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0002_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.AlterField(
            model_name='commerce',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
