# Generated by Django 4.2 on 2025-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0003_delete_subscriber_alter_commerce_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce',
            name='message',
            field=models.CharField(max_length=200),
        ),
    ]
