# Generated by Django 4.2 on 2025-03-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0004_alter_commerce_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commerce',
            name='subject',
            field=models.CharField(max_length=70),
        ),
    ]
