# Generated by Django 4.2 on 2025-03-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gp', '0005_alter_commerce_message_alter_commerce_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commerce',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
